#!perl

use 5.010;
use strict;
use warnings;

use App::ProgUtils;
use Perinci::CmdLine::Any;

# AUTHORITY
# DATE
# DIST
# VERSION

our %SPEC;

$SPEC{progless} = {
    v => 1.1,
    summary => 'Show program file with `less`',
    description => <<'_',

Basically

    % progless PROG

is roughly the same as:

    % less `which PROG`

except that it offers tab completion and can also search PROG in the current
directory or normal path (e.g. `progless ../bin/foo`).

_
    args => {
        program => {
            schema => 'filename*',
            req => 1,
            pos => 0,
            completion => $App::ProgUtils::_complete_program,
        },
    },
    deps => {
        prog => 'less',
    },
};
sub progless {
    my %args = @_;
    exec "less", App::ProgUtils::_search_program($args{program});
    # [200]; # unreached
}

Perinci::CmdLine::Any->new(
    url => '/main/progless',
    read_config => 0,
    read_env => 0,
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

Basic usage:

 % progless mpath
