#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use App::ProgUtils;
use Perinci::CmdLine::Any;

our %SPEC;
$SPEC{proglist} = {
    v => 1.1,
    summary => 'List programs matching query',
    args => {
        query => {
            schema => 're*',
            req => 1,
            pos => 0,
        },
    },
    examples => [
        {
            argv => [qw/font/],
            test => 0,
            'x.doc.show_result'=>0,
        },
    ],
};
sub proglist {
    require File::Which;

    my %args = @_;

    my $re = $args{query};

    my @res;
    for my $dir (split /:/, $ENV{PATH}) {
        opendir my $dh, $dir or next;
        for my $e (readdir $dh) {
            next if $e eq '.' || $e eq '..';
            next if -d $e;
            next unless $e =~ $re;
            push @res, $e;
        }
    }
    [200, "OK", \@res];
}

Perinci::CmdLine::Any->new(
    url => '/main/proglist',
)->run;

# ABSTRACT:
# PODNAME:
